use std::borrow::Cow;

use silkenweb::{
    attribute::{AsAttribute, Attribute},
    html_element,
};

html_element!(
    ui5-icon<web_sys::HtmlElement> {
        attributes {
            accessible-name: String,
            interactive: bool,
            name: Icon,
            show-tooltip: bool,
        }
    }
);

#[derive(Eq, PartialEq, Copy, Clone)]
pub enum Icon {
    Accelerated,
    Accept,
    AccidentalLeave,
    AccountingDocumentVerification,
    Account,
    Action,
    ActionSettings,
    Activate,
    Activities,
    Activity2,
    ActivityAssignedToGoal,
    ActivityIndividual,
    ActivityItems,
    AddActivity2,
    AddActivity,
    AddContact,
    AddCoursebook,
    AddDocument,
    AddEmployee,
    AddEquipment,
    AddFavorite,
    AddFilter,
    AddFolder,
    Add,
    AddPhoto,
    AddProcess,
    AddProduct,
    AddressBook,
    Addresses,
    Alert,
    AlongStackedChart,
    AlphabeticalOrder,
    AppearOffline,
    Appointment2,
    Appointment,
    Approvals,
    AreaChart,
    Arobase,
    ArrowBottom,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowTop,
    AttachmentAudio,
    AttachmentEPub,
    AttachmentHtml,
    Attachment,
    AttachmentPhoto,
    AttachmentTextFile,
    AttachmentVideo,
    AttachmentZipFile,
    Away,
    Background,
    BackToTop,
    Badge,
    BarChart,
    BarCode,
    Basket,
    BatchPayments,
    BbydActiveSales,
    BbydDashboard,
    Bed,
    Begin,
    Bell,
    BlankTag2,
    BlankTag,
    Blur,
    BoldText,
    Bookmark2,
    Bookmark,
    Border,
    BoStrategyManagement,
    BrokenLink,
    BrowseFolder,
    BubbleChart,
    Building,
    BulletText,
    Burglary,
    BusinessByDesign,
    BusinessCard,
    BusinessObjectsExperience,
    BusinessObjectsExplorer,
    BusinessObjectsMobile,
    BusinessOne,
    BusPublicTransport,
    Busy,
    Calendar,
    Call,
    Camera,
    Cancel,
    CancelMaintenance,
    CancelShare,
    CapitalProjects,
    Card,
    CargoTrain,
    CarRental,
    Cart2,
    Cart3,
    Cart4,
    Cart5,
    CartApproval,
    CartFull,
    Cart,
    Cause,
    ChainLink,
    Chalkboard,
    ChartAxis,
    ChartTreeMap,
    ChartTableView,
    CheckAvailability,
    Checklist2,
    ChecklistItem2,
    ChecklistItem,
    Checklist,
    ChevronPhase2,
    ChevronPhase,
    ChoroplethChart,
    CircleTask2,
    CircleTask,
    CitizenConnect,
    ClearAll,
    ClearFilter,
    ClinicalOrder,
    ClinicalTastTracker,
    CloseCommandField,
    Cloud,
    Co,
    Collaborate,
    CollapseAll,
    CollapseGroup,
    Collapse,
    CollectionsInsight,
    CollectionsManagement,
    Collision,
    ColorFill,
    ColumnChartDualAxis,
    Combine,
    CommandLineInterfaces,
    Comment,
    CommissionCheck,
    CompanyView,
    Compare2,
    Compare,
    Competitor,
    Complete,
    Connected,
    Contacts,
    Copy,
    CourseBook,
    CourseProgram,
    CreateEntryTime,
    CreateForm,
    Create,
    CreateLeaveRequest,
    CreateSession,
    CreditCard,
    CrmSales,
    CrmServiceManager,
    Crop,
    CrossedLineChart,
    Curriculum,
    CursorArrow,
    CustomerAndContacts,
    CustomerAndSupplier,
    CustomerBriefing,
    CustomerFinancialFactSheet,
    CustomerHistory,
    Customer,
    CustomerOrderEntry,
    CustomerView,
    Customize,
    Database,
    DateTime,
    Decision,
    Decline,
    DecreaseLineHeight,
    Delete,
    DesktopMobile,
    DetailLess,
    DetailMore,
    DetailView,
    DeveloperSettings,
    Dimension,
    Disconnected,
    Discussion2,
    Discussion,
    Dishwasher,
    Display,
    DisplayMore,
    DocAttachment,
    Doctor,
    Document,
    Documents,
    DocumentText,
    DonutChart,
    Down,
    DownloadFromCloud,
    Download,
    DrawRectangle,
    DrillDown,
    DrillUp,
    Dropdown,
    DropDownList,
    Duplicate,
    EamWorkOrder,
    ECare,
    Edit,
    EditOutside,
    Education,
    ELearning,
    Electrocardiogram,
    ElectronicMedicalRecord,
    Email,
    EmailRead,
    EmployeeApprovals,
    Employee,
    EmployeeLookup,
    EmployeePane,
    EmployeeRejections,
    Endoscopy,
    EndUserExperienceMonitoring,
    EnergySavingLightbulb,
    EnterMore,
    Eraser,
    Error,
    Example,
    ExcelAttachment,
    ExitFullScreen,
    ExpandAll,
    ExpandGroup,
    Expand,
    ExpenseReport,
    Explorer,
    Factory,
    Fallback,
    FamilyCare,
    FamilyProtection,
    Favorite,
    FavoriteList,
    FaxMachine,
    Feedback,
    FeederArrow,
    Feed,
    FilterAnalytics,
    FilterFacets,
    FilterFields,
    Filter,
    Flag2,
    Flag,
    Flight,
    FobWatch,
    Folder2,
    FolderBlank,
    FolderFull,
    Folder,
    Form,
    Forward,
    Fridge,
    FullScreen,
    FullStackedChart,
    FullStackedColumnChart,
    FunctionalLocation,
    Future,
    Fx,
    GanttBars,
    GeneralLeaveRequest,
    GenerateShortcut,
    GeographicBubbleChart,
    Globe,
    Goal,
    Goalseek,
    Grid,
    Group2,
    Group,
    Header,
    Heading1,
    Heading2,
    Heading3,
    Headset,
    Heart2,
    Heart,
    HeatingCooling,
    HeatmapChart,
    HelloWorld,
    Hide,
    Hint,
    History,
    Home,
    HomeShare,
    HorizontalBarChart2,
    HorizontalBarChart,
    HorizontalBulletChart,
    HorizontalCombinationChart,
    HorizontalGrip,
    HorizontalStackedChart,
    HorizontalWaterfallChart,
    HrApproval,
    IdeaWall,
    ImageViewer,
    Inbox,
    Incident,
    IncomingCall,
    IncreaseLineHeight,
    Indent,
    Information,
    Initiative,
    InProgress,
    InspectDown,
    Inspection,
    Inspect,
    Instance,
    InsuranceCar,
    InsuranceHouse,
    InsuranceLife,
    InternetBrowser,
    Inventory,
    Ipad2,
    Ipad,
    Iphone2,
    Iphone,
    ItalicText,
    ItHost,
    ItInstance,
    ItSystem,
    Jam,
    JourneyArrive,
    JourneyChange,
    JourneyDepart,
    KeyboardAndMouse,
    Key,
    KeyUserSettings,
    KpiCorporatePerformance,
    KpiManagingMyArea,
    Lab,
    Laptop,
    Lateness,
    Lead,
    LeadOutdated,
    Leads,
    LearningAssistant,
    Legend,
    Less,
    Letter,
    Lightbulb,
    LineChartDualAxis,
    LineChart,
    LineCharts,
    LineChartTimeAxis,
    List,
    Loan,
    LocateMe,
    Locked,
    Log,
    Machine,
    ManagerInsight,
    Manager,
    Map2,
    Map3,
    Map,
    MarketingCampaign,
    MasterTaskTriangle2,
    MasterTaskTriangle,
    Meal,
    Measure,
    MeasurementDocument,
    MeasuringPoint,
    MediaForward,
    MediaPause,
    MediaPlay,
    MediaReverse,
    MediaRewind,
    MeetingRoom,
    Megamenu,
    Menu2,
    Menu,
    MessageError,
    MessageInformation,
    MessagePopup,
    MessageSuccess,
    MessageWarning,
    Microphone,
    Mileage,
    Minimize,
    MirroredTaskCircle2,
    MirroredTaskCircle,
    MoneyBills,
    MonitorPayments,
    Move,
    MriScan,
    MultipleBarChart,
    MultipleLineChart,
    MultiplePieChart,
    MultipleRadarChart,
    MultiselectAll,
    MultiSelect,
    MultiselectNone,
    MySalesOrder,
    MyView,
    NavBack,
    NavigationDownArrow,
    NavigationLeftArrow,
    NavigationRightArrow,
    NavigationUpArrow,
    Negative,
    NetweaverBusinessClient,
    Newspaper,
    NotEditable,
    Notes,
    Notification2,
    Notification,
    NumberedText,
    NumberSign,
    Nurse,
    NutritionActivity,
    OfficialService,
    OffsiteWork,
    OpenCommandField,
    OpenFolder,
    Opportunities,
    Opportunity,
    OrderStatus,
    OrgChart,
    Outbox,
    Outdent,
    OutgoingCall,
    Overflow,
    Overlay,
    OverviewChart,
    Paging,
    PaidLeave,
    PaintBucket,
    Palette,
    PaperPlane,
    PassengerTrain,
    Paste,
    Past,
    Pause,
    PaymentApproval,
    PdfAttachment,
    PdfReader,
    Pending,
    PerDiem,
    Performance,
    Permission,
    PersonnelView,
    PersonPlaceholder,
    Pharmacy,
    Phone,
    PhotoVoltaic,
    PhysicalActivity,
    Picture,
    PieChart,
    PipelineAnalysis,
    Pixelate,
    Play,
    Pool,
    PopupWindow,
    Positive,
    Post,
    PptAttachment,
    Present,
    PrimaryKey,
    Print,
    Private,
    Process,
    Product,
    ProgramTriangles2,
    ProgramTriangles,
    ProjectDefinitionTriangle2,
    ProjectDefinitionTriangle,
    Projector,
    Provision,
    PullDown,
    PushpinOff,
    PushpinOn,
    Puzzle,
    QrCode,
    QualityIssue,
    QuestionMark,
    RadarChart,
    Receipt,
    Record,
    Redo,
    Refresh,
    Repost,
    Request,
    Reset,
    ResizeCorner,
    ResizeHorizontal,
    Resize,
    ResizeVertical,
    Response,
    Responsive,
    Restart,
    RetailStore,
    RetailStoreManager,
    RhombusMilestone2,
    RhombusMilestone,
    Role,
    S4hana,
    SalesDocument,
    SalesNotification,
    SalesOrderItem,
    SalesOrder,
    SalesQuote,
    SapBox,
    SapLogoShape,
    SapUi5,
    Save,
    ScatterChart,
    Scissors,
    ScreenSplitOne,
    ScreenSplitThree,
    ScreenSplitTwo,
    Search,
    Settings,
    Share2,
    Share,
    Shelf,
    Shield,
    ShippingStatus,
    Shortcut,
    ShowEdit,
    Show,
    Signature,
    SimplePayment,
    Simulate,
    SlimArrowDown,
    SlimArrowLeft,
    SlimArrowRight,
    SlimArrowUp,
    Soccer,
    Soccor,
    Sonography,
    SortAscending,
    SortDescending,
    SortingRanking,
    Sort,
    Sound,
    SoundLoud,
    SoundOff,
    SourceCode,
    Split,
    StatusCompleted,
    StatusCritical,
    StatusError,
    StatusInactive,
    StatusInProcess,
    StatusNegative,
    StatusPositive,
    Step,
    Stethoscope,
    Stop,
    Strikethrough,
    StudyLeave,
    SubwayTrain,
    Suitcase,
    Sum,
    Supplier,
    Survey,
    SwitchClasses,
    SwitchViews,
    Synchronize,
    Syntax,
    Syringe,
    SysAdd,
    SysBack2,
    SysBack,
    SysCancel2,
    SysCancel,
    SysEnter2,
    SysEnter,
    SysFind,
    SysFindNext,
    SysFirstPage,
    SysHelp2,
    SysHelp,
    SysLastPage,
    SysMinus,
    SysMonitor,
    SysNextPage,
    SysPrevPage,
    SystemExit2,
    SystemExit,
    TableChart,
    TableColumn,
    TableRow,
    TableView,
    TagCloudChart,
    Tag,
    Tags,
    TargetGroup,
    Task,
    Taxi,
    TechnicalObject,
    Temperature,
    TextAlignCenter,
    TextAlignJustified,
    TextAlignLeft,
    TextAlignRight,
    TextColor,
    TextFormatting,
    Text,
    Theater,
    ThingType,
    ThumbDown,
    ThumbUp,
    TimeAccount,
    TimeEntryRequest,
    TimeOvertime,
    Timesheet,
    ToasterDown,
    ToasterTop,
    ToasterUp,
    ToBeReviewed,
    ToolsOpportunity,
    Touch,
    Translate,
    TravelExpense,
    TravelExpenseReport,
    TravelItinerary,
    TravelRequest,
    Tree,
    TrendDown,
    TrendUp,
    TripReport,
    TriState,
    TwoKeys,
    UiNotifications,
    Umbrella,
    UnderlineText,
    Undo,
    Unfavorite,
    Unlocked,
    UnpaidLeave,
    Unwired,
    Up,
    Upload,
    UploadToCloud,
    UpstackedChart,
    UserEdit,
    UserSettings,
    Validate,
    ValueHelp,
    VdsFile,
    VehicleRepair,
    VerticalBarChart2,
    VerticalBarChart,
    VerticalBulletChart,
    VerticalGrip,
    VerticalStackedChart,
    VerticalWaterfallChart,
    Video,
    Visits,
    Waiver,
    Wallet,
    Warning2,
    Warning,
    WashingMachine,
    WeatherProofing,
    WebCam,
    Widgets,
    WindowsDoors,
    WorkflowTasks,
    WorkHistory,
    World,
    WoundsDoc,
    Wrench,
    WriteNewDocument,
    WriteNew,
    XRay,
    ZoomIn,
    ZoomOut,
}

impl Attribute for Icon {
    fn text(&self) -> Option<Cow<str>> {
        let text = match self {
            // This isn't quite as simple as converting Pascal case to Kebab case, so we can't use a
            // macro.
            Icon::Accelerated => "accelerated",
            Icon::Accept => "accept",
            Icon::AccidentalLeave => "accidental-leave",
            Icon::AccountingDocumentVerification => "accounting-document-verification",
            Icon::Account => "account",
            Icon::Action => "action",
            Icon::ActionSettings => "action-settings",
            Icon::Activate => "activate",
            Icon::Activities => "activities",
            Icon::Activity2 => "activity-2",
            Icon::ActivityAssignedToGoal => "activity-assigned-to-goal",
            Icon::ActivityIndividual => "activity-individual",
            Icon::ActivityItems => "activity-items",
            Icon::AddActivity2 => "add-activity-2",
            Icon::AddActivity => "add-activity",
            Icon::AddContact => "add-contact",
            Icon::AddCoursebook => "add-coursebook",
            Icon::AddDocument => "add-document",
            Icon::AddEmployee => "add-employee",
            Icon::AddEquipment => "add-equipment",
            Icon::AddFavorite => "add-favorite",
            Icon::AddFilter => "add-filter",
            Icon::AddFolder => "add-folder",
            Icon::Add => "add",
            Icon::AddPhoto => "add-photo",
            Icon::AddProcess => "add-process",
            Icon::AddProduct => "add-product",
            Icon::AddressBook => "address-book",
            Icon::Addresses => "addresses",
            Icon::Alert => "alert",
            Icon::AlongStackedChart => "along-stacked-chart",
            Icon::AlphabeticalOrder => "alphabetical-order",
            Icon::AppearOffline => "appear-offline",
            Icon::Appointment2 => "appointment-2",
            Icon::Appointment => "appointment",
            Icon::Approvals => "approvals",
            Icon::AreaChart => "area-chart",
            Icon::Arobase => "arobase",
            Icon::ArrowBottom => "arrow-bottom",
            Icon::ArrowDown => "arrow-down",
            Icon::ArrowLeft => "arrow-left",
            Icon::ArrowRight => "arrow-right",
            Icon::ArrowTop => "arrow-top",
            Icon::AttachmentAudio => "attachment-audio",
            Icon::AttachmentEPub => "attachment-e-pub",
            Icon::AttachmentHtml => "attachment-html",
            Icon::Attachment => "attachment",
            Icon::AttachmentPhoto => "attachment-photo",
            Icon::AttachmentTextFile => "attachment-text-file",
            Icon::AttachmentVideo => "attachment-video",
            Icon::AttachmentZipFile => "attachment-zip-file",
            Icon::Away => "away",
            Icon::Background => "background",
            Icon::BackToTop => "back-to-top",
            Icon::Badge => "badge",
            Icon::BarChart => "bar-chart",
            Icon::BarCode => "bar-code",
            Icon::Basket => "basket",
            Icon::BatchPayments => "batch-payments",
            Icon::BbydActiveSales => "bbyd-active-sales",
            Icon::BbydDashboard => "bbyd-dashboard",
            Icon::Bed => "bed",
            Icon::Begin => "begin",
            Icon::Bell => "bell",
            Icon::BlankTag2 => "blank-tag-2",
            Icon::BlankTag => "blank-tag",
            Icon::Blur => "blur",
            Icon::BoldText => "bold-text",
            Icon::Bookmark2 => "bookmark-2",
            Icon::Bookmark => "bookmark",
            Icon::Border => "border",
            Icon::BoStrategyManagement => "bo-strategy-management",
            Icon::BrokenLink => "broken-link",
            Icon::BrowseFolder => "browse-folder",
            Icon::BubbleChart => "bubble-chart",
            Icon::Building => "building",
            Icon::BulletText => "bullet-text",
            Icon::Burglary => "burglary",
            Icon::BusinessByDesign => "business-by-design",
            Icon::BusinessCard => "business-card",
            Icon::BusinessObjectsExperience => "business-objects-experience",
            Icon::BusinessObjectsExplorer => "business-objects-explorer",
            Icon::BusinessObjectsMobile => "business-objects-mobile",
            Icon::BusinessOne => "business-one",
            Icon::BusPublicTransport => "bus-public-transport",
            Icon::Busy => "busy",
            Icon::Calendar => "calendar",
            Icon::Call => "call",
            Icon::Camera => "camera",
            Icon::Cancel => "cancel",
            Icon::CancelMaintenance => "cancel-maintenance",
            Icon::CancelShare => "cancel-share",
            Icon::CapitalProjects => "capital-projects",
            Icon::Card => "card",
            Icon::CargoTrain => "cargo-train",
            Icon::CarRental => "car-rental",
            Icon::Cart2 => "cart-2",
            Icon::Cart3 => "cart-3",
            Icon::Cart4 => "cart-4",
            Icon::Cart5 => "cart-5",
            Icon::CartApproval => "cart-approval",
            Icon::CartFull => "cart-full",
            Icon::Cart => "cart",
            Icon::Cause => "cause",
            Icon::ChainLink => "chain-link",
            Icon::Chalkboard => "chalkboard",
            Icon::ChartAxis => "chart-axis",
            Icon::ChartTreeMap => "Chart-Tree-Map",
            Icon::ChartTableView => "chart-table-view",
            Icon::CheckAvailability => "check-availability",
            Icon::Checklist2 => "checklist-2",
            Icon::ChecklistItem2 => "checklist-item-2",
            Icon::ChecklistItem => "checklist-item",
            Icon::Checklist => "checklist",
            Icon::ChevronPhase2 => "chevron-phase-2",
            Icon::ChevronPhase => "chevron-phase",
            Icon::ChoroplethChart => "choropleth-chart",
            Icon::CircleTask2 => "circle-task-2",
            Icon::CircleTask => "circle-task",
            Icon::CitizenConnect => "citizen-connect",
            Icon::ClearAll => "clear-all",
            Icon::ClearFilter => "clear-filter",
            Icon::ClinicalOrder => "clinical-order",
            Icon::ClinicalTastTracker => "clinical-tast-tracker",
            Icon::CloseCommandField => "close-command-field",
            Icon::Cloud => "cloud",
            Icon::Co => "co",
            Icon::Collaborate => "collaborate",
            Icon::CollapseAll => "collapse-all",
            Icon::CollapseGroup => "collapse-group",
            Icon::Collapse => "collapse",
            Icon::CollectionsInsight => "collections-insight",
            Icon::CollectionsManagement => "collections-management",
            Icon::Collision => "collision",
            Icon::ColorFill => "color-fill",
            Icon::ColumnChartDualAxis => "column-chart-dual-axis",
            Icon::Combine => "combine",
            Icon::CommandLineInterfaces => "command-line-interfaces",
            Icon::Comment => "comment",
            Icon::CommissionCheck => "commission-check",
            Icon::CompanyView => "company-view",
            Icon::Compare2 => "compare-2",
            Icon::Compare => "compare",
            Icon::Competitor => "competitor",
            Icon::Complete => "complete",
            Icon::Connected => "connected",
            Icon::Contacts => "contacts",
            Icon::Copy => "copy",
            Icon::CourseBook => "course-book",
            Icon::CourseProgram => "course-program",
            Icon::CreateEntryTime => "create-entry-time",
            Icon::CreateForm => "create-form",
            Icon::Create => "create",
            Icon::CreateLeaveRequest => "create-leave-request",
            Icon::CreateSession => "create-session",
            Icon::CreditCard => "credit-card",
            Icon::CrmSales => "crm-sales",
            Icon::CrmServiceManager => "crm-service-manager",
            Icon::Crop => "crop",
            Icon::CrossedLineChart => "crossed-line-chart",
            Icon::Curriculum => "curriculum",
            Icon::CursorArrow => "cursor-arrow",
            Icon::CustomerAndContacts => "customer-and-contacts",
            Icon::CustomerAndSupplier => "customer-and-supplier",
            Icon::CustomerBriefing => "customer-briefing",
            Icon::CustomerFinancialFactSheet => "customer-financial-fact-sheet",
            Icon::CustomerHistory => "customer-history",
            Icon::Customer => "customer",
            Icon::CustomerOrderEntry => "customer-order-entry",
            Icon::CustomerView => "customer-view",
            Icon::Customize => "customize",
            Icon::Database => "database",
            Icon::DateTime => "date-time",
            Icon::Decision => "decision",
            Icon::Decline => "decline",
            Icon::DecreaseLineHeight => "decrease-line-height",
            Icon::Delete => "delete",
            Icon::DesktopMobile => "desktop-mobile",
            Icon::DetailLess => "detail-less",
            Icon::DetailMore => "detail-more",
            Icon::DetailView => "detail-view",
            Icon::DeveloperSettings => "developer-settings",
            Icon::Dimension => "dimension",
            Icon::Disconnected => "disconnected",
            Icon::Discussion2 => "discussion-2",
            Icon::Discussion => "discussion",
            Icon::Dishwasher => "dishwasher",
            Icon::Display => "display",
            Icon::DisplayMore => "display-more",
            Icon::DocAttachment => "doc-attachment",
            Icon::Doctor => "doctor",
            Icon::Document => "document",
            Icon::Documents => "documents",
            Icon::DocumentText => "document-text",
            Icon::DonutChart => "donut-chart",
            Icon::Down => "down",
            Icon::DownloadFromCloud => "download-from-cloud",
            Icon::Download => "download",
            Icon::DrawRectangle => "draw-rectangle",
            Icon::DrillDown => "drill-down",
            Icon::DrillUp => "drill-up",
            Icon::Dropdown => "dropdown",
            Icon::DropDownList => "drop-down-list",
            Icon::Duplicate => "duplicate",
            Icon::EamWorkOrder => "eam-work-order",
            Icon::ECare => "e-care",
            Icon::Edit => "edit",
            Icon::EditOutside => "edit-outside",
            Icon::Education => "education",
            Icon::ELearning => "e-learning",
            Icon::Electrocardiogram => "electrocardiogram",
            Icon::ElectronicMedicalRecord => "electronic-medical-record",
            Icon::Email => "email",
            Icon::EmailRead => "email-read",
            Icon::EmployeeApprovals => "employee-approvals",
            Icon::Employee => "employee",
            Icon::EmployeeLookup => "employee-lookup",
            Icon::EmployeePane => "employee-pane",
            Icon::EmployeeRejections => "employee-rejections",
            Icon::Endoscopy => "endoscopy",
            Icon::EndUserExperienceMonitoring => "end-user-experience-monitoring",
            Icon::EnergySavingLightbulb => "energy-saving-lightbulb",
            Icon::EnterMore => "enter-more",
            Icon::Eraser => "eraser",
            Icon::Error => "error",
            Icon::Example => "example",
            Icon::ExcelAttachment => "excel-attachment",
            Icon::ExitFullScreen => "exit-full-screen",
            Icon::ExpandAll => "expand-all",
            Icon::ExpandGroup => "expand-group",
            Icon::Expand => "expand",
            Icon::ExpenseReport => "expense-report",
            Icon::Explorer => "explorer",
            Icon::Factory => "factory",
            Icon::Fallback => "fallback",
            Icon::FamilyCare => "family-care",
            Icon::FamilyProtection => "family-protection",
            Icon::Favorite => "favorite",
            Icon::FavoriteList => "favorite-list",
            Icon::FaxMachine => "fax-machine",
            Icon::Feedback => "feedback",
            Icon::FeederArrow => "feeder-arrow",
            Icon::Feed => "feed",
            Icon::FilterAnalytics => "filter-analytics",
            Icon::FilterFacets => "filter-facets",
            Icon::FilterFields => "filter-fields",
            Icon::Filter => "filter",
            Icon::Flag2 => "flag-2",
            Icon::Flag => "flag",
            Icon::Flight => "flight",
            Icon::FobWatch => "fob-watch",
            Icon::Folder2 => "folder-2",
            Icon::FolderBlank => "folder-blank",
            Icon::FolderFull => "folder-full",
            Icon::Folder => "folder",
            Icon::Form => "form",
            Icon::Forward => "forward",
            Icon::Fridge => "fridge",
            Icon::FullScreen => "full-screen",
            Icon::FullStackedChart => "full-stacked-chart",
            Icon::FullStackedColumnChart => "full-stacked-column-chart",
            Icon::FunctionalLocation => "functional-location",
            Icon::Future => "future",
            Icon::Fx => "fx",
            Icon::GanttBars => "gantt-bars",
            Icon::GeneralLeaveRequest => "general-leave-request",
            Icon::GenerateShortcut => "generate-shortcut",
            Icon::GeographicBubbleChart => "geographic-bubble-chart",
            Icon::Globe => "globe",
            Icon::Goal => "goal",
            Icon::Goalseek => "goalseek",
            Icon::Grid => "grid",
            Icon::Group2 => "group-2",
            Icon::Group => "group",
            Icon::Header => "header",
            Icon::Heading1 => "heading1",
            Icon::Heading2 => "heading2",
            Icon::Heading3 => "heading3",
            Icon::Headset => "headset",
            Icon::Heart2 => "heart-2",
            Icon::Heart => "heart",
            Icon::HeatingCooling => "heating-cooling",
            Icon::HeatmapChart => "heatmap-chart",
            Icon::HelloWorld => "hello-world",
            Icon::Hide => "hide",
            Icon::Hint => "hint",
            Icon::History => "history",
            Icon::Home => "home",
            Icon::HomeShare => "home-share",
            Icon::HorizontalBarChart2 => "horizontal-bar-chart-2",
            Icon::HorizontalBarChart => "horizontal-bar-chart",
            Icon::HorizontalBulletChart => "horizontal-bullet-chart",
            Icon::HorizontalCombinationChart => "horizontal-combination-chart",
            Icon::HorizontalGrip => "horizontal-grip",
            Icon::HorizontalStackedChart => "horizontal-stacked-chart",
            Icon::HorizontalWaterfallChart => "horizontal-waterfall-chart",
            Icon::HrApproval => "hr-approval",
            Icon::IdeaWall => "idea-wall",
            Icon::ImageViewer => "image-viewer",
            Icon::Inbox => "inbox",
            Icon::Incident => "incident",
            Icon::IncomingCall => "incoming-call",
            Icon::IncreaseLineHeight => "increase-line-height",
            Icon::Indent => "indent",
            Icon::Information => "information",
            Icon::Initiative => "initiative",
            Icon::InProgress => "in-progress",
            Icon::InspectDown => "inspect-down",
            Icon::Inspection => "inspection",
            Icon::Inspect => "inspect",
            Icon::Instance => "instance",
            Icon::InsuranceCar => "insurance-car",
            Icon::InsuranceHouse => "insurance-house",
            Icon::InsuranceLife => "insurance-life",
            Icon::InternetBrowser => "internet-browser",
            Icon::Inventory => "inventory",
            Icon::Ipad2 => "ipad-2",
            Icon::Ipad => "ipad",
            Icon::Iphone2 => "iphone-2",
            Icon::Iphone => "iphone",
            Icon::ItalicText => "italic-text",
            Icon::ItHost => "it-host",
            Icon::ItInstance => "it-instance",
            Icon::ItSystem => "it-system",
            Icon::Jam => "jam",
            Icon::JourneyArrive => "journey-arrive",
            Icon::JourneyChange => "journey-change",
            Icon::JourneyDepart => "journey-depart",
            Icon::KeyboardAndMouse => "keyboard-and-mouse",
            Icon::Key => "key",
            Icon::KeyUserSettings => "key-user-settings",
            Icon::KpiCorporatePerformance => "kpi-corporate-performance",
            Icon::KpiManagingMyArea => "kpi-managing-my-area",
            Icon::Lab => "lab",
            Icon::Laptop => "laptop",
            Icon::Lateness => "lateness",
            Icon::Lead => "lead",
            Icon::LeadOutdated => "lead-outdated",
            Icon::Leads => "leads",
            Icon::LearningAssistant => "learning-assistant",
            Icon::Legend => "legend",
            Icon::Less => "less",
            Icon::Letter => "letter",
            Icon::Lightbulb => "lightbulb",
            Icon::LineChartDualAxis => "line-chart-dual-axis",
            Icon::LineChart => "line-chart",
            Icon::LineCharts => "line-charts",
            Icon::LineChartTimeAxis => "line-chart-time-axis",
            Icon::List => "list",
            Icon::Loan => "loan",
            Icon::LocateMe => "locate-me",
            Icon::Locked => "locked",
            Icon::Log => "log",
            Icon::Machine => "machine",
            Icon::ManagerInsight => "manager-insight",
            Icon::Manager => "manager",
            Icon::Map2 => "map-2",
            Icon::Map3 => "map-3",
            Icon::Map => "map",
            Icon::MarketingCampaign => "marketing-campaign",
            Icon::MasterTaskTriangle2 => "master-task-triangle-2",
            Icon::MasterTaskTriangle => "master-task-triangle",
            Icon::Meal => "meal",
            Icon::Measure => "measure",
            Icon::MeasurementDocument => "measurement-document",
            Icon::MeasuringPoint => "measuring-point",
            Icon::MediaForward => "media-forward",
            Icon::MediaPause => "media-pause",
            Icon::MediaPlay => "media-play",
            Icon::MediaReverse => "media-reverse",
            Icon::MediaRewind => "media-rewind",
            Icon::MeetingRoom => "meeting-room",
            Icon::Megamenu => "megamenu",
            Icon::Menu2 => "menu2",
            Icon::Menu => "menu",
            Icon::MessageError => "message-error",
            Icon::MessageInformation => "message-information",
            Icon::MessagePopup => "message-popup",
            Icon::MessageSuccess => "message-success",
            Icon::MessageWarning => "message-warning",
            Icon::Microphone => "microphone",
            Icon::Mileage => "mileage",
            Icon::Minimize => "minimize",
            Icon::MirroredTaskCircle2 => "mirrored-task-circle-2",
            Icon::MirroredTaskCircle => "mirrored-task-circle",
            Icon::MoneyBills => "money-bills",
            Icon::MonitorPayments => "monitor-payments",
            Icon::Move => "move",
            Icon::MriScan => "mri-scan",
            Icon::MultipleBarChart => "multiple-bar-chart",
            Icon::MultipleLineChart => "multiple-line-chart",
            Icon::MultiplePieChart => "multiple-pie-chart",
            Icon::MultipleRadarChart => "multiple-radar-chart",
            Icon::MultiselectAll => "multiselect-all",
            Icon::MultiSelect => "multi-select",
            Icon::MultiselectNone => "multiselect-none",
            Icon::MySalesOrder => "my-sales-order",
            Icon::MyView => "my-view",
            Icon::NavBack => "nav-back",
            Icon::NavigationDownArrow => "navigation-down-arrow",
            Icon::NavigationLeftArrow => "navigation-left-arrow",
            Icon::NavigationRightArrow => "navigation-right-arrow",
            Icon::NavigationUpArrow => "navigation-up-arrow",
            Icon::Negative => "negative",
            Icon::NetweaverBusinessClient => "Netweaver-business-client",
            Icon::Newspaper => "newspaper",
            Icon::NotEditable => "not-editable",
            Icon::Notes => "notes",
            Icon::Notification2 => "notification-2",
            Icon::Notification => "notification",
            Icon::NumberedText => "numbered-text",
            Icon::NumberSign => "number-sign",
            Icon::Nurse => "nurse",
            Icon::NutritionActivity => "nutrition-activity",
            Icon::OfficialService => "official-service",
            Icon::OffsiteWork => "offsite-work",
            Icon::OpenCommandField => "open-command-field",
            Icon::OpenFolder => "open-folder",
            Icon::Opportunities => "opportunities",
            Icon::Opportunity => "opportunity",
            Icon::OrderStatus => "order-status",
            Icon::OrgChart => "org-chart",
            Icon::Outbox => "outbox",
            Icon::Outdent => "outdent",
            Icon::OutgoingCall => "outgoing-call",
            Icon::Overflow => "overflow",
            Icon::Overlay => "overlay",
            Icon::OverviewChart => "overview-chart",
            Icon::Paging => "paging",
            Icon::PaidLeave => "paid-leave",
            Icon::PaintBucket => "paint-bucket",
            Icon::Palette => "palette",
            Icon::PaperPlane => "paper-plane",
            Icon::PassengerTrain => "passenger-train",
            Icon::Paste => "paste",
            Icon::Past => "past",
            Icon::Pause => "pause",
            Icon::PaymentApproval => "payment-approval",
            Icon::PdfAttachment => "pdf-attachment",
            Icon::PdfReader => "pdf-reader",
            Icon::Pending => "pending",
            Icon::PerDiem => "per-diem",
            Icon::Performance => "performance",
            Icon::Permission => "permission",
            Icon::PersonnelView => "personnel-view",
            Icon::PersonPlaceholder => "person-placeholder",
            Icon::Pharmacy => "pharmacy",
            Icon::Phone => "phone",
            Icon::PhotoVoltaic => "photo-voltaic",
            Icon::PhysicalActivity => "physical-activity",
            Icon::Picture => "picture",
            Icon::PieChart => "pie-chart",
            Icon::PipelineAnalysis => "pipeline-analysis",
            Icon::Pixelate => "pixelate",
            Icon::Play => "play",
            Icon::Pool => "pool",
            Icon::PopupWindow => "popup-window",
            Icon::Positive => "positive",
            Icon::Post => "post",
            Icon::PptAttachment => "ppt-attachment",
            Icon::Present => "present",
            Icon::PrimaryKey => "primary-key",
            Icon::Print => "print",
            Icon::Private => "private",
            Icon::Process => "process",
            Icon::Product => "product",
            Icon::ProgramTriangles2 => "program-triangles-2",
            Icon::ProgramTriangles => "program-triangles",
            Icon::ProjectDefinitionTriangle2 => "project-definition-triangle-2",
            Icon::ProjectDefinitionTriangle => "project-definition-triangle",
            Icon::Projector => "projector",
            Icon::Provision => "provision",
            Icon::PullDown => "pull-down",
            Icon::PushpinOff => "pushpin-off",
            Icon::PushpinOn => "pushpin-on",
            Icon::Puzzle => "puzzle",
            Icon::QrCode => "qr-code",
            Icon::QualityIssue => "quality-issue",
            Icon::QuestionMark => "question-mark",
            Icon::RadarChart => "radar-chart",
            Icon::Receipt => "receipt",
            Icon::Record => "record",
            Icon::Redo => "redo",
            Icon::Refresh => "refresh",
            Icon::Repost => "repost",
            Icon::Request => "request",
            Icon::Reset => "reset",
            Icon::ResizeCorner => "resize-corner",
            Icon::ResizeHorizontal => "resize-horizontal",
            Icon::Resize => "resize",
            Icon::ResizeVertical => "resize-vertical",
            Icon::Response => "response",
            Icon::Responsive => "responsive",
            Icon::Restart => "restart",
            Icon::RetailStore => "retail-store",
            Icon::RetailStoreManager => "retail-store-manager",
            Icon::RhombusMilestone2 => "rhombus-milestone-2",
            Icon::RhombusMilestone => "rhombus-milestone",
            Icon::Role => "role",
            Icon::S4hana => "s4hana",
            Icon::SalesDocument => "sales-document",
            Icon::SalesNotification => "sales-notification",
            Icon::SalesOrderItem => "sales-order-item",
            Icon::SalesOrder => "sales-order",
            Icon::SalesQuote => "sales-quote",
            Icon::SapBox => "sap-box",
            Icon::SapLogoShape => "sap-logo-shape",
            Icon::SapUi5 => "sap-ui5",
            Icon::Save => "save",
            Icon::ScatterChart => "scatter-chart",
            Icon::Scissors => "scissors",
            Icon::ScreenSplitOne => "screen-split-one",
            Icon::ScreenSplitThree => "screen-split-three",
            Icon::ScreenSplitTwo => "screen-split-two",
            Icon::Search => "search",
            Icon::Settings => "settings",
            Icon::Share2 => "share-2",
            Icon::Share => "share",
            Icon::Shelf => "shelf",
            Icon::Shield => "shield",
            Icon::ShippingStatus => "shipping-status",
            Icon::Shortcut => "shortcut",
            Icon::ShowEdit => "show-edit",
            Icon::Show => "show",
            Icon::Signature => "signature",
            Icon::SimplePayment => "simple-payment",
            Icon::Simulate => "simulate",
            Icon::SlimArrowDown => "slim-arrow-down",
            Icon::SlimArrowLeft => "slim-arrow-left",
            Icon::SlimArrowRight => "slim-arrow-right",
            Icon::SlimArrowUp => "slim-arrow-up",
            Icon::Soccer => "soccer",
            Icon::Soccor => "soccor",
            Icon::Sonography => "sonography",
            Icon::SortAscending => "sort-ascending",
            Icon::SortDescending => "sort-descending",
            Icon::SortingRanking => "sorting-ranking",
            Icon::Sort => "sort",
            Icon::Sound => "sound",
            Icon::SoundLoud => "sound-loud",
            Icon::SoundOff => "sound-off",
            Icon::SourceCode => "source-code",
            Icon::Split => "split",
            Icon::StatusCompleted => "status-completed",
            Icon::StatusCritical => "status-critical",
            Icon::StatusError => "status-error",
            Icon::StatusInactive => "status-inactive",
            Icon::StatusInProcess => "status-in-process",
            Icon::StatusNegative => "status-negative",
            Icon::StatusPositive => "status-positive",
            Icon::Step => "step",
            Icon::Stethoscope => "stethoscope",
            Icon::Stop => "stop",
            Icon::Strikethrough => "strikethrough",
            Icon::StudyLeave => "study-leave",
            Icon::SubwayTrain => "subway-train",
            Icon::Suitcase => "suitcase",
            Icon::Sum => "sum",
            Icon::Supplier => "supplier",
            Icon::Survey => "survey",
            Icon::SwitchClasses => "switch-classes",
            Icon::SwitchViews => "switch-views",
            Icon::Synchronize => "synchronize",
            Icon::Syntax => "syntax",
            Icon::Syringe => "syringe",
            Icon::SysAdd => "sys-add",
            Icon::SysBack2 => "sys-back-2",
            Icon::SysBack => "sys-back",
            Icon::SysCancel2 => "sys-cancel-2",
            Icon::SysCancel => "sys-cancel",
            Icon::SysEnter2 => "sys-enter-2",
            Icon::SysEnter => "sys-enter",
            Icon::SysFind => "sys-find",
            Icon::SysFindNext => "sys-find-next",
            Icon::SysFirstPage => "sys-first-page",
            Icon::SysHelp2 => "sys-help-2",
            Icon::SysHelp => "sys-help",
            Icon::SysLastPage => "sys-last-page",
            Icon::SysMinus => "sys-minus",
            Icon::SysMonitor => "sys-monitor",
            Icon::SysNextPage => "sys-next-page",
            Icon::SysPrevPage => "sys-prev-page",
            Icon::SystemExit2 => "system-exit-2",
            Icon::SystemExit => "system-exit",
            Icon::TableChart => "table-chart",
            Icon::TableColumn => "table-column",
            Icon::TableRow => "table-row",
            Icon::TableView => "table-view",
            Icon::TagCloudChart => "tag-cloud-chart",
            Icon::Tag => "tag",
            Icon::Tags => "tags",
            Icon::TargetGroup => "target-group",
            Icon::Task => "task",
            Icon::Taxi => "taxi",
            Icon::TechnicalObject => "technical-object",
            Icon::Temperature => "temperature",
            Icon::TextAlignCenter => "text-align-center",
            Icon::TextAlignJustified => "text-align-justified",
            Icon::TextAlignLeft => "text-align-left",
            Icon::TextAlignRight => "text-align-right",
            Icon::TextColor => "text-color",
            Icon::TextFormatting => "text-formatting",
            Icon::Text => "text",
            Icon::Theater => "theater",
            Icon::ThingType => "thing-type",
            Icon::ThumbDown => "thumb-down",
            Icon::ThumbUp => "thumb-up",
            Icon::TimeAccount => "time-account",
            Icon::TimeEntryRequest => "time-entry-request",
            Icon::TimeOvertime => "time-overtime",
            Icon::Timesheet => "timesheet",
            Icon::ToasterDown => "toaster-down",
            Icon::ToasterTop => "toaster-top",
            Icon::ToasterUp => "toaster-up",
            Icon::ToBeReviewed => "to-be-reviewed",
            Icon::ToolsOpportunity => "tools-opportunity",
            Icon::Touch => "touch",
            Icon::Translate => "translate",
            Icon::TravelExpense => "travel-expense",
            Icon::TravelExpenseReport => "travel-expense-report",
            Icon::TravelItinerary => "travel-itinerary",
            Icon::TravelRequest => "travel-request",
            Icon::Tree => "tree",
            Icon::TrendDown => "trend-down",
            Icon::TrendUp => "trend-up",
            Icon::TripReport => "trip-report",
            Icon::TriState => "tri-state",
            Icon::TwoKeys => "two-keys",
            Icon::UiNotifications => "ui-notifications",
            Icon::Umbrella => "umbrella",
            Icon::UnderlineText => "underline-text",
            Icon::Undo => "undo",
            Icon::Unfavorite => "unfavorite",
            Icon::Unlocked => "unlocked",
            Icon::UnpaidLeave => "unpaid-leave",
            Icon::Unwired => "unwired",
            Icon::Up => "up",
            Icon::Upload => "upload",
            Icon::UploadToCloud => "upload-to-cloud",
            Icon::UpstackedChart => "upstacked-chart",
            Icon::UserEdit => "user-edit",
            Icon::UserSettings => "user-settings",
            Icon::Validate => "validate",
            Icon::ValueHelp => "value-help",
            Icon::VdsFile => "vds-file",
            Icon::VehicleRepair => "vehicle-repair",
            Icon::VerticalBarChart2 => "vertical-bar-chart-2",
            Icon::VerticalBarChart => "vertical-bar-chart",
            Icon::VerticalBulletChart => "vertical-bullet-chart",
            Icon::VerticalGrip => "vertical-grip",
            Icon::VerticalStackedChart => "vertical-stacked-chart",
            Icon::VerticalWaterfallChart => "vertical-waterfall-chart",
            Icon::Video => "video",
            Icon::Visits => "visits",
            Icon::Waiver => "waiver",
            Icon::Wallet => "wallet",
            Icon::Warning2 => "warning2",
            Icon::Warning => "warning",
            Icon::WashingMachine => "washing-machine",
            Icon::WeatherProofing => "weather-proofing",
            Icon::WebCam => "web-cam",
            Icon::Widgets => "widgets",
            Icon::WindowsDoors => "windows-doors",
            Icon::WorkflowTasks => "workflow-tasks",
            Icon::WorkHistory => "work-history",
            Icon::World => "world",
            Icon::WoundsDoc => "wounds-doc",
            Icon::Wrench => "wrench",
            Icon::WriteNewDocument => "write-new-document",
            Icon::WriteNew => "write-new",
            Icon::XRay => "x-ray",
            Icon::ZoomIn => "zoom-in",
            Icon::ZoomOut => "zoom-out",
        };
        Some(text.into())
    }
}

impl AsAttribute<Icon> for Icon {}
